apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: juice-shop
  labels:
    app: juice-shop
    service: juice-shop
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    name: http
  selector:
    app: juice-shop 